name: ${name}
version: ${version}
main: me.lukiiy.discordBridge.DiscordBridge
api-version: '1.16'
load: STARTUP
authors: [Lukiiy]
description: ${desc}
website: ${web}
softdepend: ["PlaceholderAPI"]
commands:
  discordbridge:
    aliases: [dcbridge, dcb]
    permission: dcbridge.cmd
    description: "The main command for DiscordBridge!"