name: ${name}
version: ${version}
main: me.lukiiy.discordBridge.DiscordBridge
api-version: '1.20'
load: STARTUP
authors: [Lukiiy]
description: ${desc}
website: ${web}
bootstrapper: me.lukiiy.discordBridge.Boot
folia-supported: true
dependencies:
  server:
    PlaceholderAPI:
      load: AFTER
      required: false
      join-classpath: false